[State]
  MintbaseAddress = ""

[Store]
  Path = "data"

[TxPool]
  WaitingTimeout = 2000000000
  MaxSize = 2000

[Consensus]
  ChangeProposerTimeout = 6000000000
  ChangeProposerDelta = 2000000000

[Network]
  Name = "zarb"
  ListenAddress = ["/ip4/0.0.0.0/tcp/8421", "/ip6/::/tcp/8421"]
  NodeKeyFile = "node_key"
  EnableNATService = true
  EnableRelay = true
  EnableMDNS = true
  EnableKademlia = true
  [Network.Bootstrap]
    Addresses = []
    MinThreshold = 8
    MaxThreshold = 16
    Period = 60000000000

[Logger]
  Colorfull = true
  [Logger.Levels]
    _capnp = "error"
    _consensus = "error"
    _grpc = "error"
    _http = "error"
    _network = "error"
    _pool = "error"
    _state = "error"
    _sync = "error"
    default = "error"

[Sync]
  Moniker = ""
  StartingTimeout = 3000000000
  HeartBeatTimeout = 5000000000
  SessionTimeout = 3000000000
  InitialBlockDownload = true
  BlockPerMessage = 10
  RequestBlockInterval = 720
  CacheSize = 500000

[Capnp]
  Enable = false
  Address = "[::]:37621"

[Http]
  Enable = false
  Address = "[::]:8081"

[GRPC]
  Enable = true
  Address = "[::]:9090"
  [GRPC.Gateway]
    Enable = true
    Address = "[::]:8080"