[State]
  [State.Store]
    Path = "data"

[TxPool]
  WaitingTimeout = 2000000000
  MaxSize = 2000

[Consensus]
  TimeoutPrepare = 3000000000
  TimeoutPrecommit = 2000000000
  DeltaDuration = 1000000000

[Network]
  Name = "zarb-testnet"
  ListenAddress = []
  NodeKeyFile = "node_key"
  EnableNATService = false
  EnableRelay = false
  EnableMDNS = true
  EnableKademlia = false
  [Network.Bootstrap]
    Addresses = []
    MinThreshold = 4
    MaxThreshold = 8
    Period = 60000000000
    Timeout = 20000000000

[Logger]
  Colorfull = true
  [Logger.Levels]
    _capnp = "error"
    _consensus = "debug"
    _http = "error"
    _network = "error"
    _pool = "error"
    _state = "info"
    _sync = "warning"
    _grpc = "error"
    default = "info"

[Sync]
  Moniker = "my-testnet-node"
  StartingTimeout = 2000000000
  HeartBeatTimeout = 5000000000
  SessionTimeout = 3000000000
  InitialBlockDownload = false
  BlockPerMessage = 10
  CacheSize = 10000

[Capnp]
  Enable = false
  Address = "[::]:37621"

[Http]
  Enable = false
  Address = "[::]:8081"

[GRPC]
  Enable = false
  Address = "[::]:9090"
  [GRPC.Gateway]
    Enable = false
    Address = "[::]:8080"