[State]
  [State.Store]
    Path = "data"

[TxPool]
  WaitingTimeout = 2000000000
  MaxSize = 2000

[Consensus]
  TimeoutPrepare = 3000000000
  TimeoutPrecommit = 2000000000
  DeltaDuration = 1000000000

[Network]
  Name = "zarb-testnet"
  ListenAddress = ["/ip4/0.0.0.0/tcp/31887", "/ip6/::/tcp/31887"]
  NodeKeyFile = "node_key"
  EnableNATService = true
  EnableRelay = true
  EnableMDNS = true
  EnableKademlia = true
  [Network.Bootstrap]
    Addresses = []
    MinThreshold = 4
    MaxThreshold = 8
    Period = 60000000000
    Timeout = 20000000000

[Logger]
  Colorfull = true
  [Logger.Levels]
    _capnp = "error"
    _consensus = "debug"
    _http = "error"
    _network = "error"
    _pool = "error"
    _state = "info"
    _sync = "warning"
    _grpc = "error"
    default = "info"

[Sync]
  Moniker = "my-testnet-sentry"
  StartingTimeout = 2000000000
  HeartBeatTimeout = 5000000000
  SessionTimeout = 3000000000
  InitialBlockDownload = true
  BlockPerMessage = 20
  CacheSize = 50000

[Capnp]
  Enable = true
  Address = "[::]:37621"

[Http]
  Enable = true
  Address = "[::]:8081"

[GRPC]
  Enable = true
  Address = "[::]:9090"
  [GRPC.Gateway]
    Enable = true
    Address = "[::]:8080"